//
//  CategoryConfigurator.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation

class  CategoryConfigurator: CategoryConfiguratorProtocol {
    
    func configure(with viewController: CategoryViewController) {
        let presenter =  CategoryPresenter(view: viewController)
        let router =  CategoryRouter(viewController: viewController)
        viewController.presenter = presenter
        presenter.router = router
    }
}
