//
//  CategoryPresenter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoryPresenter: CategoryPresenterProtocol {
    
    
    func configureView() {
        
    }
    weak var view: CategoryViewProtocol!
    var interactor: CategoryInteractorProtocol!
    var router: CategoryRouterProtocol!
    
    required init(view: CategoryViewProtocol) {
        self.view = view
    }
    func openThing() {
        router.showThingScene()
    }
    func backButtonClicked() {
        router.showCategoriesScene()
    }
}
