//
//  CategoryViewController.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoryViewController: UIViewController, CategoryViewProtocol {

	
    var presenter: CategoryPresenterProtocol!
    var configurator: CategoryConfiguratorProtocol = CategoryConfigurator()
    let selfToThing = "CategoryToThingSegue"
	override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
    }
    @IBAction func openThingButton(_ sender: Any) {
        presenter.openThing()
    }
    
    @IBAction func backClickedButton(_ sender: Any) {
        presenter.backButtonClicked()
    }
}
