//
//  CategoryRouter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoryRouter: CategoryRouterProtocol {
   
    
    
    weak var viewController: CategoryViewController!
    init(viewController: CategoryViewController) {
        self.viewController = viewController
    }
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // prepare here some data for destination viewController
    }
    func showThingScene() {
        viewController.performSegue(withIdentifier: viewController.selfToThing, sender: nil)
    }
    func showCategoriesScene() {
        viewController.dismiss(animated: true, completion: nil)
    }
}
