//
//  SignInProtocols.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation
import UIKit
//MARK: Router -
protocol SignInRouterProtocol: class {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
    func showSignUpScene()
    func showSignInScene()
}
//MARK: Presenter -
protocol SignInPresenterProtocol: class {
    var router:  SignInRouterProtocol! { set get }
    func configureView()
    func signUpButtonClicked()
    func signInButtonClicked()
}

//MARK: Interactor -
protocol SignInInteractorProtocol: class {

}

//MARK: View -
protocol SignInViewProtocol: class {

}

//MARK: Configurator -
protocol SignInConfiguratorProtocol: class {
    func configure(with viewController: SignInViewController)
}

