//
//  SignInPresenter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class SignInPresenter: SignInPresenterProtocol {
   
    weak var view: SignInViewProtocol!
    var interactor: SignInInteractorProtocol!
    var router: SignInRouterProtocol!
    
    required init(view: SignInViewProtocol) {
        self.view = view
    }
    func configureView() {
    
    }
    
    func signUpButtonClicked() {
        router.showSignUpScene()
    }
    
    func signInButtonClicked() {
        router.showSignInScene()
    }
}
