//
//  SignInRouter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class SignInRouter: SignInRouterProtocol {
   
    weak var viewController: SignInViewController!
    init(viewController: SignInViewController) {
        self.viewController = viewController
    }
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // prepare here some data for destination viewController
    }
    func showSignUpScene() {
        viewController.performSegue(withIdentifier: viewController.selfToSignUpSegueName, sender: nil)
    }
    func showSignInScene() {
        viewController.performSegue(withIdentifier: viewController.selfToTabBar, sender: nil)
    }
}
