//
//  SignInConfigurator.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation

class  SignInConfigurator: SignInConfiguratorProtocol {
    
    func configure(with viewController: SignInViewController) {
        let presenter =  SignInPresenter(view: viewController)
        let router =  SignInRouter(viewController: viewController)
        viewController.presenter = presenter
        presenter.router = router
    }
}
