//
//  MainCardViewController.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class MainCardViewController: UIView, MainCardViewProtocol {

	
    var presenter: MainCardPresenterProtocol!
    var configurator: MainCardConfiguratorProtocol = MainCardConfigurator()
    
    @IBOutlet var view: UIView!
    override init(frame: CGRect) {
        super.init(frame: frame)
        xibSetup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        xibSetup()
    }
    
    private func xibSetup() {
        configurator.configure(with: self)
        presenter.configureView()
        Bundle.main.loadNibNamed("MainCardViewController", owner: self, options: nil)
        addSubview(view)
        view.frame = self.bounds
        view.autoresizingMask = [.flexibleHeight, .flexibleWidth]
        setUpPropertyView(view: view)
    }
    //  сюда настройки вьюхи запихнуть
    private func setUpPropertyView(view: UIView) {
        
    }

}
