//
//  MainCardRouter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class MainCardRouter: MainCardRouterProtocol {
    
    
    weak var viewController: MainCardViewController!
    init(viewController: MainCardViewController) {
        self.viewController = viewController
    }
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // prepare here some data for destination viewController
    }
}
