//
//  MainCardPresenter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class MainCardPresenter: MainCardPresenterProtocol {
    func configureView() {
        
    }
    
    weak var view: MainCardViewProtocol!
    var interactor: MainCardInteractorProtocol!
    var router: MainCardRouterProtocol!
    
    required init(view: MainCardViewProtocol) {
        self.view = view
    }

}
