//
//  MainCardProtocols.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation
import UIKit
//MARK: Router -
protocol MainCardRouterProtocol: class {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)

}
//MARK: Presenter -
protocol MainCardPresenterProtocol: class {
    var router:  MainCardRouterProtocol! { set get }
    func configureView()
}

//MARK: Interactor -
protocol MainCardInteractorProtocol: class {

}

//MARK: View -
protocol MainCardViewProtocol: class {

}

//MARK: Configurator -
protocol MainCardConfiguratorProtocol: class {
    func configure(with viewController: MainCardViewController)
}

