//
//  SignUpViewController.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class SignUpViewController: UIViewController, SignUpViewProtocol {

	
    var presenter: SignUpPresenterProtocol!
    var configurator: SignUpConfiguratorProtocol = SignUpConfigurator()
    let selfToSignUpSegueName = "SignUpToSignUpSegue"
	override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
    }
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        presenter.router.prepare(for: segue, sender: sender)
    }

    @IBAction func backButtonClicked(_ sender: Any) {
        presenter.backButtonClicked()
    }
}
