//
//  SignUpPresenter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class SignUpPresenter: SignUpPresenterProtocol {
    
    
    weak var view: SignUpViewProtocol!
    var interactor: SignUpInteractorProtocol!
    var router: SignUpRouterProtocol!
    
    required init(view: SignUpViewProtocol) {
        self.view = view
    }
    func configureView() {
        
    }
    
    func backButtonClicked() {
        router.showSignInScene()
    }
}
