//
//  SignUpConfigurator.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation

class  SignUpConfigurator: SignUpConfiguratorProtocol {
    
    func configure(with viewController: SignUpViewController) {
        let presenter =  SignUpPresenter(view: viewController)
        let router =  SignUpRouter(viewController: viewController)
        viewController.presenter = presenter
        presenter.router = router
    }
}
