//
//  CategoriesRouter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoriesRouter: CategoriesRouterProtocol {
    weak var viewController: CategoriesViewController!
    init(viewController: CategoriesViewController) {
        self.viewController = viewController
    }
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // prepare here some data for destination viewController
    }
    func showCategoryScene() {
        viewController.performSegue(withIdentifier: viewController.selfToCategory, sender: nil)
    }
    
}
