//
//  CategoriesPresenter.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoriesPresenter: CategoriesPresenterProtocol {
    
    
    weak var view: CategoriesViewProtocol!
    var interactor: CategoriesInteractorProtocol!
    var router: CategoriesRouterProtocol!
    
    required init(view: CategoriesViewProtocol) {
        self.view = view
    }
    func configureView() {
        
    }
    
    func openCategory() {
        router.showCategoryScene()
    }
}
