//
//  CategoriesConfigurator.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation

class  CategoriesConfigurator: CategoriesConfiguratorProtocol {
    
    func configure(with viewController: CategoriesViewController) {
        let presenter =  CategoriesPresenter(view: viewController)
        let router =  CategoriesRouter(viewController: viewController)
        viewController.presenter = presenter
        presenter.router = router
    }
}
