//
//  CategoriesProtocols.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation
import UIKit
//MARK: Router -
protocol CategoriesRouterProtocol: class {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
    func showCategoryScene()
}
//MARK: Presenter -
protocol CategoriesPresenterProtocol: class {
    var router:  CategoriesRouterProtocol! { set get }
    func configureView()
    func openCategory()
}

//MARK: Interactor -
protocol CategoriesInteractorProtocol: class {

}

//MARK: View -
protocol CategoriesViewProtocol: class {

}

//MARK: Configurator -
protocol CategoriesConfiguratorProtocol: class {
    func configure(with viewController: CategoriesViewController)
}

