//
//  CategoriesViewController.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 08/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class CategoriesViewController: UIViewController, CategoriesViewProtocol {

	
    var presenter: CategoriesPresenterProtocol!
    var configurator: CategoriesConfiguratorProtocol = CategoriesConfigurator()
    let selfToCategory = "CategoriesToCategorySegue"
	override func viewDidLoad() {
        super.viewDidLoad()
        configurator.configure(with: self)
        presenter.configureView()
    }
    @IBAction func openCategory(_ sender: Any) {
        presenter.openCategory()
    }
    
}
