//
//  CardProtocols.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation
import UIKit
//MARK: Router -
protocol CardRouterProtocol: class {
    func prepare(for segue: UIStoryboardSegue, sender: Any?)

}
//MARK: Presenter -
protocol CardPresenterProtocol: class {
    var router:  CardRouterProtocol! { set get }
    func configureView()
}

//MARK: Interactor -
protocol CardInteractorProtocol: class {

}

//MARK: View -
protocol CardViewProtocol: class {

}

//MARK: Configurator -
protocol CardConfiguratorProtocol: class {
    func configure(with viewController: CardViewController)
}

