//
//  CardConfigurator.swift
//  CreativeWorkshop
//
//  Created Maxim Spiridonov on 18/02/2019.
//  Copyright © 2019 Maxim Spiridonov. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import Foundation

class  CardConfigurator: CardConfiguratorProtocol {
    func configureView() {
        
    }
    func configure(with viewController: CardViewController) {
        let presenter =  CardPresenter(view: viewController)
        let router =  CardRouter(viewController: viewController)
        viewController.presenter = presenter
        presenter.router = router
    }
}
